# Generated by Django 2.1.2 on 2020-08-19 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_prompts', '0002_auto_20200819_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='status',
            new_name='recorded',
        ),
    ]
