# Generated by Django 2.1.2 on 2020-10-19 18:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('text_prompts', '0003_auto_20200819_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
