# Generated by Django 2.1.2 on 2020-10-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_prompts', '0004_auto_20201019_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
