# Generated by Django 2.1.2 on 2020-10-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_prompts', '0006_auto_20201020_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='data',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='uid',
        ),
        migrations.AddField(
            model_name='sentence',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
