# Generated by Django 2.1.2 on 2020-11-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_recordings', '0002_recordings_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordings',
            name='textid',
            field=models.IntegerField(),
        ),
    ]
