# Generated by Django 2.1.2 on 2020-11-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_recordings', '0006_auto_20201102_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordings',
            name='audiofile',
            field=models.FileField(upload_to='recordings/'),
        ),
    ]
