# Generated by Django 2.1.2 on 2020-11-06 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio_recordings', '0007_auto_20201103_2141'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recordings',
            new_name='Recording',
        ),
    ]
