# Generated by Django 2.1.2 on 2020-11-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_recordings', '0010_auto_20201109_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='verified',
            field=models.BooleanField(null=True),
        ),
    ]
