# Generated by Django 2.1.2 on 2020-11-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_recordings', '0011_auto_20201110_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='verified',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
    ]
