# Generated by Django 2.1.2 on 2020-11-10 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_recordings', '0013_auto_20201110_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='verified',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
